### ISSUE TITLE
Logo in top left corner needs correcting

### ISSUE THREAD

**Issue by pauld123** [pauld123/CI-Design#2]
The logo I knocked up quickly but it needs correcting. The Flame is right but we need to get the logo to look more like the one on the CI Forum, but to work on a light grey background. Could someone help with that please?

**Comment by dturner123** [comment]
Have you got the original file?

**Comment by pauld123** [comment]
No I only had the files on the CI website graphics pages, but I had to photoshop them as best I could.

**Comment by pauld123** [comment]
I have updated it to match the one on CI a bit more. Again just a photoshop of the image on the CI website.

**Comment by dturner123** [comment]
I have created a vector version of the logo - included is an SVG, PNG and the Adobe Illustrator file - [http://s376031790.websitehome.co.uk/CodeigniterLogo.zip](http://s376031790.websitehome.co.uk/CodeigniterLogo.zip)
